"""Seed 05_glossary.csv (pending, empty approved_ar by design) from the curated candidates in 04_game_context.md §7."""
import csv, os, io, sys
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
BASE = os.path.dirname(os.path.abspath(__file__))
T = [  # term, type, should_translate, notes
    ("Nephilim", "race", "decide", "player race; transliteration proposed; Qur'anic echo issue"),
    ("Angel", "mechanic", "translate", "bonded spirit"), ("Angelic Sigil", "mechanic", "translate", ""),
    ("Angelic Grace", "mechanic", "translate", "transform meter"), ("Angel Ascension", "mechanic", "translate", "transformation"),
    ("Angel Sense", "mechanic", "translate", ""),
    ("Lunarin", "deity", "transliterate", "the Church's god"), ("Lunitarian", "faction", "transliterate", "root"),
    ("Lunitarian Church", "faction", "translate", "root + Church"),
    ("The Divine", "deity", "translate", ""), ("Divine Throne", "place", "translate", ""), ("Holy Lineage", "faction", "translate", "ruling body of Church"),
    ("Archspire", "place", "decide", "FR kept Archspire"), ("Archspire Cathedral", "place", "decide", ""), ("Gildenarch", "place", "transliterate", "the city"),
    ("Southern Ward", "place", "translate", ""), ("Grimhaven", "place", "transliterate", ""), ("Gilded Ward", "place", "translate", ""), ("Forsaken Streets", "place", "translate", ""),
    ("Ramshorn Keep", "place", "decide", "FR chateau de Ramshorn"), ("Shoreditch Prison", "place", "decide", "transliterate Shoreditch + translate Prison"),
    ("Elk Grove Academy", "place", "decide", ""), ("Moore Manor", "place", "decide", ""), ("Godsreach Spire", "place", "decide", "FR Fleche de Godsreach"),
    ("Sanctus Clypeus", "place", "transliterate", "Latin; Order hall"), ("Transmitorium", "mechanic", "decide", ""), ("War Table", "mechanic", "translate", "mission select"),
    ("Excursion", "mechanic", "translate", "a run"),
    ("Abraxas Stone", "story", "decide", "Abraxas transliterate; also wizard Abraxas Godsbane"), ("Dead Gods", "story", "translate", ""),
    ("Dry Rot King", "boss", "translate", ""), ("E'frae", "boss", "transliterate", "Dry Rot King's name"), ("Lord of Perdition", "boss", "translate", ""),
    ("Mahkteah", "boss", "transliterate", ""), ("Mahkten", "faction", "transliterate", "his people"),
    ("Eye of the Abyss", "boss", "translate", ""), ("Aegoroth", "boss", "transliterate", ""), ("The Warden", "boss", "translate", ""),
    ("Flesh-Wrought Egregore", "boss", "decide", "Egregore?"), ("Tyrigon", "boss", "transliterate", "dragon"),
    ("Valahk-Nor", "boss", "transliterate", "normalize hyphen; General"), ("Felwyl", "boss", "transliterate", "spelling drift Fewyl/Felwil"),
    ("The Withered", "epithet", "translate", ""), ("The Ascended", "epithet", "translate", ""),
    ("Infernal Legion", "faction", "translate", ""), ("Hellgrowth", "story", "translate", ""), ("Infernal Flora", "story", "translate", ""),
    ("Red Bloom", "story", "translate", ""), ("Red Gift", "story", "translate", ""), ("The Garden", "story", "translate", "cult concept"),
    ("The Reborn", "faction", "translate", "Hellgrowth cult"), ("Shepherds", "faction", "translate", "cult name for demons"),
    ("Crimson Concordat", "story", "translate", ""), ("Order of the Crimson Moon", "faction", "translate", ""), ("Knights of the Crimson Moon", "faction", "translate", ""),
    ("Divine Oath", "rank", "translate", ""), ("Moonlight Oath", "rank", "translate", ""), ("Midnight Oath", "rank", "translate", ""),
    ("Crimson Oath", "rank", "translate", ""), ("Keeper's Oath", "rank", "translate", ""),
    ("Apostate", "faction", "translate", ""), ("Apostate Hunts", "story", "translate", ""), ("Specters", "faction", "translate", "assassins"),
    ("Crusader", "faction", "translate", ""), ("Covenant Cleric", "faction", "translate", ""),
    ("Inquisition", "faction", "translate", ""), ("Inquisitor", "faction", "translate", ""), ("Pyresworn", "faction", "decide", ""),
    ("Cardinal", "title", "translate", ""), ("Archbishop", "title", "translate", ""), ("Bishop", "title", "translate", ""), ("Scribe", "title", "translate", ""), ("Prefect", "title", "translate", ""),
    ("The Veil", "story", "translate", "barrier between realms"), ("The Coil", "story", "decide", ""), ("Demiurge", "story", "translate", ""),
    ("Eden", "place", "decide", "the world; religious weight"),
    ("Luderaeon", "place", "transliterate", "angel realm; normalize Ludereon"), ("Akyreon", "place", "transliterate", "demon realm; Iridaeon variant"),
    ("Infernus", "place", "translate", ""), ("Purgatory", "place", "translate", ""), ("Celestial Mountains", "place", "translate", ""),
    ("Rite of Desolation", "story", "translate", ""), ("Great Reconstruction", "story", "translate", ""), ("War of the Gods", "story", "translate", ""),
    ("The Sundering", "story", "translate", ""), ("Sentinels", "faction", "translate", ""),
    ("Velchoria", "place", "transliterate", ""), ("Velchorian Empire", "place", "decide", ""), ("Luminar", "place", "transliterate", "capital"),
    ("Karsiv", "place", "transliterate", ""), ("Karsivite Orthodoxy", "faction", "decide", ""),
    ("Armaea", "place", "transliterate", ""), ("Belwayne", "place", "transliterate", ""), ("Litinstang", "place", "transliterate", ""),
    ("Nachtendale", "place", "transliterate", ""), ("Saedrys", "place", "transliterate", ""), ("Caragus", "place", "transliterate", ""), ("Treveyan", "place", "transliterate", ""),
    ("Rot Kin", "faction", "translate", ""), ("Saedric", "faction", "decide", ""), ("Cain", "character", "decide", "vampire progenitor"),
    ("Cain's Covenant", "story", "translate", ""), ("Clan Moore", "faction", "transliterate", ""), ("Telvaught", "faction", "transliterate", ""),
    ("Feral", "state", "translate", "vampire/Nephilim"),
    ("Death Knights", "enemy", "translate", ""), ("Nac-Fei", "enemy", "transliterate", ""), ("Knight Terrors", "enemy", "translate", ""),
    ("Demon Brutes", "enemy", "translate", ""), ("Imps", "enemy", "translate", ""), ("Undead Captains", "enemy", "translate", ""),
    ("Cultists", "enemy", "translate", ""), ("Feral Vampires", "enemy", "translate", ""),
    ("Soul Energy", "mechanic", "translate", ""), ("Drakes", "mechanic", "transliterate", "currency"), ("Holy Phases", "story", "translate", "liturgy"), ("Blood Moon", "story", "translate", ""),
    ("St. Uriel", "character", "decide", ""), ("St. Enoch", "character", "decide", ""), ("Maedrael", "character", "transliterate", "Archangel"),
    ("Apothos", "character", "transliterate", ""), ("Azrael", "character", "decide", ""),
    ("Gallow's Wraith", "epithet", "translate", "Gallant's epithet"), ("Lore Scrolls", "item", "translate", ""), ("Legendary Scraps", "item", "translate", ""),
    ("Crescent Tags", "item", "translate", ""), ("Divine Ember", "item", "translate", ""), ("Revenant Crown", "item", "translate", ""), ("Cipher Fragment", "item", "translate", ""),
    ("Nachtstahl", "place", "transliterate", ""), ("Weapon Art", "mechanic", "translate", ""), ("Boon", "mechanic", "translate", ""), ("Trinket", "mechanic", "translate", ""),
    ("Blueprint", "mechanic", "translate", ""), ("Mana", "mechanic", "translate", ""), ("Stamina", "mechanic", "translate", ""), ("Skulls", "mechanic", "translate", "difficulty tier"),
    ("Hellrift", "mechanic", "translate", ""), ("Nexus Gate", "mechanic", "translate", ""), ("Purify", "mechanic", "translate", ""), ("Loadout", "mechanic", "translate", ""), ("Bounty", "mechanic", "translate", ""),
    ("Gallant", "character", "transliterate", "Gallant Alexander, Knight Commander; hard G = ق"), ("Knight Commander", "title", "translate", ""),
    ("Solomon Moore", "character", "transliterate", ""), ("Cardinal Mathias", "character", "transliterate", "+ translate Cardinal"),
    ("Mereda", "character", "transliterate", "Librarian, f"), ("Lotte Ananta", "character", "transliterate", "Merchant, m"), ("Gajov", "character", "transliterate", "Blacksmith, m"),
    ("Nahnias", "character", "transliterate", "possibly the Angel"), ("Lesandra", "character", "transliterate", ""), ("Anya", "character", "transliterate", ""),
    ("Selandris", "character", "transliterate", ""), ("Alonious", "character", "transliterate", "Emperor"), ("Ciaran Telvaught", "character", "transliterate", ""),
    ("Irvine Gaertner", "character", "transliterate", ""), ("Bishop Aaron", "character", "decide", ""), ("Siron", "character", "transliterate", ""),
]
with open(os.path.join(BASE, "05_glossary.csv"), "w", newline="", encoding="utf-8") as f:
    w = csv.writer(f); w.writerow(["source_term", "type", "should_translate", "approved_ar", "status", "notes"])
    for t in T:
        w.writerow([t[0], t[1], t[2], "", "pending", t[3]])
print("glossary rows", len(T))
assert len({t[0] for t in T}) == len(T)
